version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

    groups:
      nextjs:
        patterns:
          - "next"
          - "react"
          - "react-dom"
          - "@next/*"
          - "eslint-config-next"

      tiptap:
        patterns:
          - "@tiptap/*"

      tailwind:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
          - "tw-animate-css"

      eslint:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "@typescript-eslint/*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
